# Generated by Django 4.2.16 on 2024-09-30 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('was_sent', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=250)),
                ('newsletter_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('subed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_app.newsletter')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_app.sub')),
            ],
        ),
    ]
