apiVersion: v1
kind: Service
metadata:
  name: newsletter-service
spec:
  selector:
    app: newsletter-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
